---
- name: Azure_Arc_Agent Deployment
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Copy Azure_Arc_Agent and chage to executable
      copy:
       connection: local
       become: yes 
       become_user: root
       src:  '/tmp/semaphore/Linux_updates.yml'
       dest: '/tmp/'
       mode: 0755
       remote_src: no
    - name: Run shell script on remote server
      #shell: sh /tmp/az_connect_linux.sh
      
   # - name: Remove shell script from remote server
      #file:
       # path: /tmp/az_connect_linux.sh
       # state: absent
