---
- name: Azure_Arc_Agent Deployment
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Copy Azure_Arc_Agent and chage to executable
      copy:
         connection: local
         become: yes 
         become_user: root
         src:  '/home/ruhsadmin/mypath.txt'
         dest: '/tmp/'
         mode: 0777
      remote_src: false
