---
- name: Copy files to remote server
  hosts: ubuntu
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: /tmp/semaphore/az_connect_linux.sh.bak
        dest: /tmp/az_connect_linux.sh.bak
        owner: semaphore
        group: semaphore
        mode: '0644'
