---
- name: Copy files to remote server
  hosts: website
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: az_connect_linux.sh
        dest: /tmp/az_connect_linux.sh
        owner: semaphore
        group: semaphore
        mode: '0644'
