---
- name: Copy files to remote server
  hosts: ubuntu
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: /tmp/semaphore/falcon-sensor_7.20.0-17306_amd64.deb
        dest: /tmp/falcon-sensor_7.20.0-17306_amd64.deb
        owner: semaphore
        group: semaphore
        mode: '0644'
