---
- name: Copy files to remote server
  hosts: website
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: crowdstrike.sh
        dest: /home/semaphore/
        owner: semaphore
        group: semaphore
        mode: '0644'
