- name: Copy folder to remote server using rsync
  hosts: website
  become: true
  tasks:
    - name: Sync folder to remote server
      copy:
        src: security_agents
        dest: /tmp/
        archive: yes
        recursive: yes
        delete: no
