---
- name: Copy files to remote server
  hosts: website
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: falcon-sensor_7.20.0-17306_amd64.deb
        dest: /home/semaphore/
        owner: semaphore
        group: semaphore
        mode: '0644'
