---
- name: Copy files to remote server
  hosts: all
  become: true
  tasks:
    - name: Copy file to remote server
      copy:
        src: /tmp/semaphore/Security_Agents
        dest: /tmp/Security_Agents
        #owner: semaphore
        #group: semaphore
        #mode: '0644'
