- name: Copy folder to remote server using rsync
  hosts: ubuntu
  become: true
  tasks:
    - name: Sync folder to remote server
      copy:
        src: /test/
        dest: /tmp/test/
        #archive: yes
        #recursive: yes
        #delete: no
