---
- name: Disable ICMP redirect support
  hosts: ubuntu
  become: true
  tasks:
    - shell: |
        echo -n 'net/ipv4/conf/all/accept_redirects = 0' >> /etc/sysctl.conf
        echo -n 'net/ipv4/conf/all/send_redirects = 0' >> /etc/sysctl.conf
        echo -n 'net/ipv6/conf/all/accept_redirects = 0' >> /etc/sysctl.conf
        #sed -i 's/-e net/ipv4/conf/all/accept_redirects = 0/net/ipv4/conf/all/accept_redirects = 0/' /etc/sysctl.conf
        #sed -i '/-e net/d' /etc/sysctl.conf
        #sed -i '/net/d' /etc/sysctl.conf
        #sysctl -p
      become_user: root
      become_method: su
