---
- name: Disable ICMP redirect support
  hosts: ubuntu
  become: true
  tasks:
    - shell: |
         sed -i '/-e net/d' /etc/sysctl.conf
         sed -i '/net/d' /etc/sysctl.conf
        #sysctl -p
      become_user: root
      become_method: su
