---
- name: Disable ICMP redirect support
  hosts: all
  become: true
  tasks:
    - shell: |
         echo  e "sysctl -w net.ipv4.conf.all.accept_redirects=0\nsysctl -w net.ipv4.conf.default.accept_redirects=0\nsysctl -w net.ipv4.conf.all.secure_redirects=0\nsysctl -w net.ipv4.conf.default.secure_redirects=0" | sudo tee -a /etc/sysctl.conf > /dev/null
         sysctl -p
      become_user: root
      become_method: su
