---
- name: Check local path
  hosts: all
  become: true
  tasks:
    - name: Check local path
      shell:
          "pwd > /home/ansible/mypath.txt"
          "cp /home/ansible/mypath.txt /tmp"
      become_user: root
      become_method: su
