---
- name: Check local path
  hosts: ubuntu
  become: true
  tasks:
    - name: Fetching
      fetch: 
        src: ~/Azure_Arc.yml
        dest: /tmp/Azure_Arc.yml
        remote_src: no
      become_user: root
      become_method: su
