---
- name: Check local path
  hosts: all
  become: true
  tasks:
    - name: checking and copying
      shell:
          "pwd > /home/ruhsadmin/mypath.txt"
      become_user: root
      become_method: su
  tasks:
    - name: Fetching
      fetch: 
        src: /home/ruhsadmin/mypath.txt
        dest: /home/ruhsadmin/myohmy.txt
        remote_src: false
      become_user: root
      become_method: su
