---
- name: Check local path
  hosts: all
  become: true
  tasks:
    - name: Check local path
      shell:
          "pwd > /home/ansible/mypath.txt"
      shell:
          "cp /home/ansible/mypath.txt /tmp"
      fetch: 
        src: /home/ansible/mypath.txt
        dest: /home/ruhsadmin/mynewpath.txt
      become_user: root
      become_method: su
