---
- name: File locate
  hosts: localhost
  become: true
  tasks:
    - name: Locate my directory
        shell: pwd > mydiectory.txt
      remote_src: false
      become_user: root
      become_method: su
