---
- name: Check local path
  hosts: all
  become: true
  tasks:
    - name: Fetching
      fetch: 
        src: /home/ruhsadmin/Azure_Arc.yml
        dest: /tmp/Azure_Arc.yml
        remote_src: false
      become_user: root
      become_method: su
