---
- name: Copy security agents and run installation scripts
  hosts: all
  become: yes
  tasks:
    
    - name: Ensure /tmp/security_agents directory exists on remote
      file:
        path: /tmp/Security_Agents
        state: directory
        mode: '0755'

    - name: Copy security_agents folder to remote server
      synchronize:
        src: /tmp/semaphore/Security_Agents/
        dest: /tmp/Security_Agents
        recursive: yes
        owner: no
        group: no
        perms: no
      delegate_to: localhost

    - name: Change permissions for the scripts
      file:
        path: "/tmp/Security_Agents/{{ item }}"
        mode: '0755'
      loop:
        - rapid7.sh
        - crowdstrike.sh

#    - name: Execute rapid7.sh
#      command: /bin/bash /tmp/security_agents/rapid7.sh
#      register: rapid7_output
#      changed_when: rapid7_output.rc != 0

#   - name: Execute crowdstrike.sh
#     command: /bin/bash /tmp/security_agents/crowdstrike.sh
#      register: crowdstrike_output
#      changed_when: crowdstrike_output.rc != 0

#   - name: Debug Rapid7 script output
#      debug:
#        msg: "{{ rapid7_output.stdout }}"

#    - name: Debug CrowdStrike script output
#      debug:
#        msg: "{{ crowdstrike_output.stdout }}"
