---
- name: Updates Ubuntu servers
  hosts: all
  become: true
  tasks:
    - apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
      become: true
      become_method: su
      ansible_become_user: ruhsadmin
