---
- name: Updates Ubuntu servers
  hosts: all
  become: true
  tasks:
    - apt:
      become: true
      become_method: su
      become_user: root
        update_cache: yes
        upgrade: full
        autoremove: yes
