---
- name: Updates Ubuntu servers
  hosts: all
  become: true
  tasks:
    - name: Update Ubuntu
      become_user: root
      become_method: sudo
    - apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
      
