---
- name: Updates Ubuntu servers
  hosts: all
  become: true
  tasks:
    - name: Update and Upgrade packages
    - apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
      become_method: su
