---
- name: Check local path
  hosts: localhost
  become: true
  tasks:
    - name: Check local path
      shell:
          "pwd > /home/ansible/mypath.txt"
      become_user: root
      become_method: su
- name: Copy file to remote
  hosts: all
  become: true
  tasks:
    - name: Copy file
      copy:
         src:  '/home/ruhsadmin/mypath.txt'
         dest: '/tmp/'
         mode: 0777
      remote_src: false
      become_user: root
      become_method: su
