---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: read file
        fetch:
           connection: local
           become_method: su
           become: yes 
           become_user: root
           delegate_to: localhost
           src: /tmp/semaphore/Linux_updates.yml
           dest: /tmp/
           mode: 0755
           remote_src: false
      
