---
- name: Updates Ubuntu servers
  hosts: all
  become: true
  tasks:
        copy:
          src: '/tmp/az_connect_linux.sh'
          dest: '/tmp/'
        remote_src: no
        become_user: root
        become_method: su
        remote_src: no
         
      
