---
- name: Copy test File
  hosts: all
  become: true
  tasks:
    - name: Copy test file
      copy:
         src: '/tmp/az_connect_linux.sh'
         dest: '/tmp/'
      become_user: root
      become_method: su
     
         
      
