---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Azure_Arc_Agent
      fetch:
         src: '/tmp/semaphore/*'
         dest: '/tmp/'
      check_mode: false
      changed_when: false
      delegate_to: localhost
         
      
