---
- name: Deploy Rapid7_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Rapid_Agent
      shell:
          "pwd > /home/ansible/mypath.txt"
       remote_src: false
      become_user: root
      become_method: su
         
      
