---
- name: Check local path
  hosts: all
  become: true
  tasks:
    - name: Check local path
      shell:
          "pwd > /home/ansible/mypath.txt"
      become_user: root
      become_method: su
  tasks:
    - name: Copy Azure_Arc_Agent and chage to executable
      copy:
         connection: local
         become: yes 
         become_user: root
         src:  '/home/ruhsadmin/mypath.txt'
         dest: '/tmp/'
         mode: 0777
      remote_src: false
         
      
