---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Azure_Arc_Agent
      copy:
       src: /tmp/semaphore/*
       dest: /tmp/
       mode: a+x
       remote_src: false

      
