---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: read file
      copy:
        connection: local
        become: yes 
        become_user: root
        src: /tmp/az_connect_linux.sh
        dest: /tmp/az_connect_linux.sh
        mode: 0755
        remote_src: false
      
