---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Azure_Arc_Agent
      copy:
         src: '/home/ansible/tes'
         dest: '/tmp/'
         owner: ansible
         group: ansible
         mode: 0644
     
         
      
