---
- name: Update web servers
  hosts: all
  remote_user: root
  tasks:
    copy:
      src: /tmp/az_connect_linux.sh
      dest: /tmp/
    remote_src: no
    become_user: root
    become_method: su
         
      
