---
- name: Deploy Azure_Arc_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Azure_Arc_Agent
      fetch:
         src: '/tmp/semaphore/*'
         dest: '/tmp/'
         remote_src: false
      check_mode: false
      changed_when: false
         
      
