---
- name: Deploy Rapid7_Agent
  hosts: all
  become: true
  tasks:
    - name: Copy Rapid_Agent
      copy:
       src: /home/ansible/security_agents/agent_installer-x86_64.sh
       dest: /tmp/agent_installer-x86_64.sh
       mode: a+x
       remote_src: false
      become_user: root
      become_method: su
         
      
