---
- name: Deploy Rapid7_Agent
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Copy Rapid_Agent
      copy:
       src: /tmp/az_connect_linux.sh
       dest: /tmp/
       mode: a+x
       remote_src: false
      become_user: root
      become_method: su
         
      
